if not exist "build" mkdir build
cd build
cmake .. -DBUILD_SHARED_LIBS:BOOL="0" -DUSE_DOUBLE_PRECISION:BOOL="1" -DINSTALL_CMAKE_FILES:BOOL="0" -DGLFW_VULKAN_STATIC:BOOL="1" -DGLFW_USE_HYBRID_HPG:BOOL="1" -DBUILD_PYBULLET:BOOL="0" 